CREATE TABLE admin (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  login VARCHAR(64) NOT NULL,
  hash VARCHAR(255) NOT NULL,
  email VARCHAR(64) NOT NULL,
  salt VARCHAR(255) NOT NULL
);

CREATE TABLE genres (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(64) NOT NULL
);

CREATE TABLE photos (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  genreid INT NOT NULL ,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (genreid) REFERENCES genres(id)
);

